# Generated by Django 4.1.3 on 2022-11-03 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0002_alter_artist_social_link"),
        ("albums", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="is_approved",
            field=models.BooleanField(
                default=False, help_text="Approve the album if its name is not explicit"
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="albums",
                to="artists.artist",
            ),
        ),
    ]
