# Generated by Django 4.1.3 on 2022-11-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="social_link",
            field=models.URLField(blank=True, default=""),
        ),
    ]
